version: "2"
services:
    nginx:
        build: ./nginx/
        ports:
            - "80:80"
        volumes:
            - /www/static/
        volumes_from:
            - web
        links:
            - web:web
        depends_on:
            - web
    # static:
    #     build: .
    #     command: python3 manage.py collectstatic --noinput
    #     volumes:
    #         - .:/code
    web:
        build: .
        expose:
            - "8000"
        command: uwsgi --http :8000 --module backend.wsgi
        volumes:
            - .:/code
        # depends_on:
        #     - static