# Generated by Django 3.2.12 on 2022-03-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatcontent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chatcontent',
            name='user',
        ),
    ]
