openapi: 3.0.2
info:
    title: ""
    version: ""
paths:
    /user/login/:
        post:
            operationId: createlogin
            description: ""
            parameters: []
            requestBody:
                content:
                    application/json:
                        schema: {}
                    application/x-www-form-urlencoded:
                        schema: {}
                    multipart/form-data:
                        schema: {}
            responses:
                "201":
                    content:
                        application/json:
                            schema: {}
                    description: ""
            tags:
                - user
