# Generated by Django 3.2.12 on 2022-02-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_upload',
        ),
    ]
