# Generated by Django 3.2.12 on 2022-03-12 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FRIEND', 'friend'), ('BLOCK', 'block')], default='FRIEND', max_length=10)),
                ('chatID', models.CharField(max_length=10, unique=True)),
                ('userFirst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_1', to=settings.AUTH_USER_MODEL)),
                ('userSecond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userFirst', 'userSecond')},
            },
        ),
    ]
